[package]
name = "RestApiServer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-rt = "2.10.0"
actix-web = "4.9.0"
dotenv = "0.15.0"
jsonwebtoken = "9.3.1"
serde = "1.0.217"
serde_json = "1.0.138"
uuid = "1.13.2"
